### PR TITLE
[Tested] Backwards Compatibility Zone_IsClientInZone

### PR DESCRIPTION
**Pull request by eyal282**
Best of both worlds. Enables both backwards compatibility and enables StrContains check, and a check for case sensitivity.

### CODE REVIEW

**Comment by Bara** [comment]
Seems like you changes from tabs to spaces? I can't load/see the changes, here on github. If yes, I'm fine with it.

Could you add a comment to the native and both forwards, why you named it to `Zone_*` before anyone ask about this prefix?

**Comment by eyal282** [comment]
> 



> Seems like you changes from tabs to spaces? I can't load/see the changes, here on github. If yes, I'm fine with it.
> 
> Could you add a comment to the native and both forwards, why you named it to `Zone_*` before anyone ask about this prefix?

Is the term "Backwards Compatibility" not enough to describe why it's named Zone_*?

**Comment by Bara** [comment]
Should be enough 👌🏻

**Comment by eyal282** [comment]
> Should be enough 👌🏻

For obvious reasons I did not put .smx in there, to avoid any complications of a possible malware in the .smx

**Pull request merged**
